# Discord bot token. If you do not have a token obtain one from https://discord.com/developers/applications
Token: 
DiscordChannelId: 

RelayToMinecraft: true
RelayToConsole: true
RelayToDiscord: true

AnnounceJoinsToDiscord: true
AnnounceQuitsToDiscord: true